import unittest
from unittest import TestCase

from ecspo import Storage, Entity, Prototype


class TestStorage(TestCase):
    def test_handle(self):
        ...
    def test_spawn(self):
        ...
    def test_despawn(self):
        ...
    def test_pool(self):
        ...
    def test_tag(self):
        ...
    def test_release(self):
        ...
    def test_set(self):
        ...
    def test_unset(self):
        ...
    def test_get(self):
        ...
    def test_has(self):
        ...


class TestEntity(TestCase):
    def test_set(self):
        ...
    def test_unset(self):
        ...
    def test_get(self):
        ...
    def test_has(self):
        ...
    def test_despawn(self):
        ...


class TestPrototype(TestCase):
    def test_reparent(self):
        ...
    def test_set(self):
        ...
    def test_build(self):
        ...


if __name__ == "__main__":
    unittest.main()
